const ItemType = {
  DIRT: 'dirt',
  GRASS: 'grass',
  STONE: 'stone',
  WOOD: 'wood',
  LEAVES: 'leaves',
  SAND: 'sand',
  COAL: 'coal',
  IRON_ORE: 'iron_ore',
  IRON_INGOT: 'iron_ingot',
  PLANKS: 'planks',
  COBBLESTONE: 'cobblestone',
  STICK: 'stick',
  WORKBENCH: 'workbench',
  WOODEN_PICKAXE: 'wooden_pickaxe',
  STONE_PICKAXE: 'stone_pickaxe',
  IRON_PICKAXE: 'iron_pickaxe',
  WOODEN_SWORD: 'wooden_sword',
  STONE_SWORD: 'stone_sword',
  IRON_SWORD: 'iron_sword',
  WOODEN_AXE: 'wooden_axe',
  STONE_AXE: 'stone_axe',
  IRON_AXE: 'iron_axe',
  MUTTON: 'mutton',
  PORKCHOP: 'porkchop',
  WOOL: 'wool',
  TORCH: 'torch',
};

const ItemInfo = {
  [ItemType.DIRT]: { name: '泥土', color: '#8B4513', icon: 'block', stackable: true, maxStack: 64, placeAs: 2 },
  [ItemType.GRASS]: { name: '草方块', color: '#4CAF50', icon: 'grass', stackable: true, maxStack: 64, placeAs: 1 },
  [ItemType.STONE]: { name: '石头', color: '#757575', icon: 'block', stackable: true, maxStack: 64, placeAs: 3 },
  [ItemType.WOOD]: { name: '原木', color: '#6D4C41', icon: 'log', stackable: true, maxStack: 64, placeAs: 4 },
  [ItemType.LEAVES]: { name: '树叶', color: '#2E7D32', icon: 'leaves', stackable: true, maxStack: 64, placeAs: 5 },
  [ItemType.SAND]: { name: '沙子', color: '#FDD835', icon: 'block', stackable: true, maxStack: 64, placeAs: 6 },
  [ItemType.COAL]: { name: '煤炭', color: '#212121', icon: 'coal', stackable: true, maxStack: 64, fuel: true },
  [ItemType.IRON_ORE]: { name: '铁矿石', color: '#FFB74D', icon: 'ore', stackable: true, maxStack: 64 },
  [ItemType.IRON_INGOT]: { name: '铁锭', color: '#B0BEC5', icon: 'ingot', stackable: true, maxStack: 64 },
  [ItemType.PLANKS]: { name: '木板', color: '#BCAAA4', icon: 'planks', stackable: true, maxStack: 64, placeAs: 10 },
  [ItemType.COBBLESTONE]: { name: '圆石', color: '#616161', icon: 'cobble', stackable: true, maxStack: 64, placeAs: 11 },
  [ItemType.STICK]: { name: '木棍', color: '#5D4037', icon: 'stick', stackable: true, maxStack: 64 },
  [ItemType.WORKBENCH]: { name: '工作台', color: '#8D6E63', icon: 'workbench', stackable: true, maxStack: 64, placeAs: 14 },
  [ItemType.WOODEN_PICKAXE]: { name: '木镐', color: '#8D6E63', icon: 'pickaxe', stackable: false, tool: true, damage: 2 },
  [ItemType.STONE_PICKAXE]: { name: '石镐', color: '#757575', icon: 'pickaxe', stackable: false, tool: true, damage: 3 },
  [ItemType.IRON_PICKAXE]: { name: '铁镐', color: '#B0BEC5', icon: 'pickaxe', stackable: false, tool: true, damage: 4 },
  [ItemType.WOODEN_SWORD]: { name: '木剑', color: '#8D6E63', icon: 'sword', stackable: false, weapon: true, damage: 4 },
  [ItemType.STONE_SWORD]: { name: '石剑', color: '#757575', icon: 'sword', stackable: false, weapon: true, damage: 5 },
  [ItemType.IRON_SWORD]: { name: '铁剑', color: '#B0BEC5', icon: 'sword', stackable: false, weapon: true, damage: 6 },
  [ItemType.WOODEN_AXE]: { name: '木斧', color: '#8D6E63', icon: 'axe', stackable: false, tool: true, damage: 3 },
  [ItemType.STONE_AXE]: { name: '石斧', color: '#757575', icon: 'axe', stackable: false, tool: true, damage: 4 },
  [ItemType.IRON_AXE]: { name: '铁斧', color: '#B0BEC5', icon: 'axe', stackable: false, tool: true, damage: 5 },
  [ItemType.MUTTON]: { name: '羊肉', color: '#E57373', icon: 'meat', stackable: true, maxStack: 64, food: 4 },
  [ItemType.PORKCHOP]: { name: '猪肉', color: '#F48FB1', icon: 'meat', stackable: true, maxStack: 64, food: 4 },
  [ItemType.WOOL]: { name: '羊毛', color: '#FAFAFA', icon: 'wool', stackable: true, maxStack: 64, placeAs: 16 },
  [ItemType.TORCH]: { name: '火把', color: '#FFD54F', icon: 'torch', stackable: true, maxStack: 64, placeAs: 13 },
};

const CraftingRecipes2x2 = [
  { input: [[ItemType.WOOD, null], [null, null]], output: { type: ItemType.PLANKS, count: 4 } },
  { input: [[ItemType.PLANKS, ItemType.PLANKS], [ItemType.PLANKS, ItemType.PLANKS]], output: { type: ItemType.WORKBENCH, count: 1 } },
  { input: [[ItemType.PLANKS, null], [ItemType.PLANKS, null]], output: { type: ItemType.STICK, count: 4 } },
  { input: [[ItemType.STONE, ItemType.STONE], [ItemType.STONE, ItemType.STONE]], output: { type: ItemType.COBBLESTONE, count: 4 } },
  { input: [[ItemType.WOOL, ItemType.WOOL], [ItemType.WOOL, ItemType.WOOL]], output: { type: ItemType.WOOL, count: 1 } },
  { input: [[ItemType.COAL, null], [ItemType.STICK, null]], output: { type: ItemType.TORCH, count: 4 } },
];

const CraftingRecipes3x3 = [
  { input: [[ItemType.PLANKS, ItemType.PLANKS, ItemType.PLANKS], [null, ItemType.STICK, null], [null, ItemType.STICK, null]], output: { type: ItemType.WOODEN_PICKAXE, count: 1 } },
  { input: [[ItemType.COBBLESTONE, ItemType.COBBLESTONE, ItemType.COBBLESTONE], [null, ItemType.STICK, null], [null, ItemType.STICK, null]], output: { type: ItemType.STONE_PICKAXE, count: 1 } },
  { input: [[ItemType.IRON_INGOT, ItemType.IRON_INGOT, ItemType.IRON_INGOT], [null, ItemType.STICK, null], [null, ItemType.STICK, null]], output: { type: ItemType.IRON_PICKAXE, count: 1 } },
  { input: [[null, ItemType.PLANKS, null], [null, ItemType.PLANKS, null], [null, ItemType.STICK, null]], output: { type: ItemType.WOODEN_SWORD, count: 1 } },
  { input: [[null, ItemType.COBBLESTONE, null], [null, ItemType.COBBLESTONE, null], [null, ItemType.STICK, null]], output: { type: ItemType.STONE_SWORD, count: 1 } },
  { input: [[null, ItemType.IRON_INGOT, null], [null, ItemType.IRON_INGOT, null], [null, ItemType.STICK, null]], output: { type: ItemType.IRON_SWORD, count: 1 } },
  { input: [[ItemType.PLANKS, ItemType.PLANKS, null], [ItemType.PLANKS, ItemType.STICK, null], [null, ItemType.STICK, null]], output: { type: ItemType.WOODEN_AXE, count: 1 } },
  { input: [[ItemType.COBBLESTONE, ItemType.COBBLESTONE, null], [ItemType.COBBLESTONE, ItemType.STICK, null], [null, ItemType.STICK, null]], output: { type: ItemType.STONE_AXE, count: 1 } },
  { input: [[ItemType.IRON_INGOT, ItemType.IRON_INGOT, null], [ItemType.IRON_INGOT, ItemType.STICK, null], [null, ItemType.STICK, null]], output: { type: ItemType.IRON_AXE, count: 1 } },
];
